<a href="https://colab.research.google.com/github/Toeylik/kku_data_mining/blob/master/Data103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np

In [56]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [57]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [58]:
np2 [0,:]

array([1, 2])

HW6 สร้างdistance metrix(mahattan and euclidean)ของnp2
โดยสร้างfuncionสำหรับคำนวณmahattan distance and euclidean distance
def euclidean(data1,data2):
#process
return dist

In [68]:
def Manhattan(data1,data2):
  distX=data1[0]-data2[0]
  return distX

In [60]:
Manhattan(np2[0,:],np2[1,:])

-2

In [69]:
def Manhattan(data1,data2):
  distX=data1[0]-data2[0]
  distY=data1[1]-data2[1]
  return distX+distY

In [ ]:
Manhattan(np2[0,:],np2[1,:])

In [62]:
dist_mat=np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j]= Manhattan(np2[i,:],np2[j,:])
dist_mat

array([[ 0., -5.,  1., -6.],
       [ 5.,  0.,  6., -1.],
       [-1., -6.,  0., -7.],
       [ 6.,  1.,  7.,  0.]])

In [64]:
np2.shape

(4, 2)

In [49]:
def Euclidean(data1,data2):
    distX = pow((data1[0]-data2[0]),2)
    distY = pow((data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [65]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

In [67]:
import math

##distance of nominal or categorical features


(extra)Puthon data stureture(Dictionary)

In [ ]:
d_A ={'a':1,2:3,3:5,'cat':6}

In [ ]:
d_A

In [ ]:
d_A['cat']

In [ ]:
d_A['dog']=[1,2,3,4]

In [ ]:
d_A

In [ ]:
del d_A['dog']

In [ ]:
d_A

In [ ]:
import pandas as pd

In [ ]:
data_dict = {'color':['red','red','green'],
                    'status':['single','married','single']}
data_dict

In [ ]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

##Categorical feature distance method#1

In [ ]:
list(data_pd.iloc[0,:])

In [ ]:
def meth1_dist(data1,data2):
    N=0
    print(f'data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feature{i} of data1 is {data1[i]} , feature{i} of data2 is {data2[i]} ')
        if data1[i] != data2[i]:
            N = N+1
            print(f'    {data1[i]} is not equal {data2[i]} : updated ({N})')
        else:
            print(f'{data1[i]} is equal {data2[i]}')
    return N/len(data1)

In [ ]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))


##Categorical feature distance method#2

In [ ]:
pd.get_dummies(data_pd)

In [ ]:
def binary_sym_dist(data1,data2):
            q =0
            rs=0
            t=0
            for i in range(len(data1)):
                if data1[i] == data2[i]:
                    if data1[i] == 1:
                        q=q+1
                    else:
                        t=t+1
                if data1[i] != data2[i]:
                     rs=rs+1
            return (rs)/(q+rs+t)

In [ ]:
binary_sym_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

##Hw 8 calculate distance matrix os data_pd_binary using binary_sym_dist()